### PR TITLE
Add tdqm dependency for progress bars.  Resolves #355.

### LINKED ISSUE #355: [BUG] tqdm is not included in `environment.yml`
Following the instructions in `CONTRIBUTING.md` leads to errors since `tqdm` is not included in the environment.  (Trivial fix.) It is included in `conda.recipe/meta.yaml` but does not seem to get installed with `pip`.  Will submit a PR shortly.

### PR DESCRIPTION
**Pull request by mforbes**
This is a minimal fix for issue #355.  Note: after running the tests, many pieces of code were reformatted.  I did not include these changes to keep the noise at a minimum.  Should I first commit a `lint` revision with the reformatted code, then rebase my changes on top?  (If so, this could be spelled out explicitly in `CONTRIBUTING.md`.  Let me know and I can include in a future documentation PR.)

I am not comfortable enough with the project's CI to figure out why this error was not caught during CI.  Does the CI provision from an environment that uses `conda/meta.yml`?  If so, we might like to add some CI provisioning from `environment.yml` directly (for developers) and from `setup.py` (for people who install from `pip`).

### CODE REVIEW

**Comment by mforbes** [comment]
BTW: I could not run all of the tests: Things stalled at "anaconda_project/internal/test/test_conda_api.py::test_resolve_dependencies_with_actual_conda_other_platforms" with this step taking close to an hour. (Mac OS X 10.14.6).

**Comment by AlbertDeFusco** [comment]
Approved!

**Comment by AlbertDeFusco** [comment]
I'll give it a try on my system with `auto_stack: 1`. I've opened a new issue for it #357

**Comment by AlbertDeFusco** [comment]
Ick, I have no idea what's up with tests. I've been having trouble with the Github actions for several weeks on this repo.

Anyway, #358 has some updates to CONTRIBUTING.md, more are certainly appreciated.

**Review by AlbertDeFusco — APPROVED** [review]

**Pull request merged**
