### PR TITLE
add user_fields field

### PR DESCRIPTION
**Pull request by cjmartian**
This adds support for a `user_fields` field that will stop warnings from happening and will allow the user to define arbitrary fields in their project.yaml as requested here: https://github.com/Anaconda-Platform/anaconda-project/issues/221

### CODE REVIEW

**Comment by cjmartian** [comment]
@jbednar No problem! I don't think I have the ability to merge the changes.

**Comment by jbednar** [comment]
I can merge, once the tests pass.

**Comment by jsignell** [comment]
Looks like some flake errors?

**Comment by mcg1969** [comment]
Closing in favor of #228. It was easier to pull the key commits into a separate branch

**Pull request closed without merging**
