### PR TITLE
Check if there is a progress bar before updating it

### LINKED ISSUE #339: Downloading a file with no `content-length` in its header fails
We have an issue with downloading a CSV file in one of the examples at examples.pyviz.org (https://github.com/pyviz-topics/examples/issues/176). Requesting this file returns a header that doesn't have a 'content-length' entry, which means that no tqdm progress bar is created. The code however expects one and thus fails in this case:

https://github.com/Anaconda-Platform/anaconda-project/blob/3394ac6c7713f949b038952eafc3f90d92f19411/anaconda_project/internal/http_client.py#L86-L88

### PR DESCRIPTION
**Pull request by maximlt**
Fixes #339 

I have seen no existing infrastructure for testing this sort of thing. I tested it on the example reported in the issue and the fix worked fine.

### CODE REVIEW

**Comment by jlstevens** [comment]
@AlbertDeFusco Looks good to me! 

As the original author of this functionality, are you happy to see this merged?

**Comment by jlstevens** [comment]
I suppose my only query is whether there are other error conditions other than the lack of the 'content-length' entry that we should know about (that mean the progress bar isn't created). Either way, this is definitely a more robust fallback.

**Comment by maximlt** [comment]
@jbednar why did you close it?

**Comment by jlstevens** [comment]
I think this is a horrible misfeature of GitHub!

Jim merged https://github.com/pyviz-topics/examples/pull/187 on `pyviz-topics` and Maxime mentioned this issue there. I think Github is closing issues across projects upon merge just for mentioning issues!

**Comment by jbednar** [comment]
Crazy! Github seems to have decided that because PR 187 on pyviz-topics/examples says "fix" near a reference to this PR, somehow that PR would close this PR. Obviously that's an incorrect inference in this case, but it also seems inappropriate to assume _any_ PR will close another PR.

**Comment by AlbertDeFusco** [comment]
Thanks for the PR. I'm going to look at getting the tests fixed and merge this.

**Comment by AlbertDeFusco** [comment]
I've fixed the test and added a changelog. This will be tagged as 0.10.2

**Comment by maximlt** [comment]
Thanks Albert!

**Review by AlbertDeFusco — APPROVED** [review]

**Pull request merged**
