### PR TITLE
progress bar for project download and extract

### PR DESCRIPTION
**Pull request by AlbertDeFusco**
project-download

Give it a try

```
conda install -c defusco/label/dev anaconda-project=0.10.0+4.g35774f5
```

### CODE REVIEW

**Comment by jlstevens** [comment]
Looks good! Here is what happened when I tried it:

image

The progress bars worked properly but now I am wondering about those warning messages. I thought it might be due to older dependency versions in my environment but when I created a fresh env I found that they remain. Any ideas?

**Comment by AlbertDeFusco** [comment]
Those warnings are from anaconda-client. Check your `~./continuum/anaconda-client/config.yml` for ssl verify entries. Some of them may be null

**Comment by jlstevens** [comment]
That fixed it, thanks!

I set both `ssl_verify` and `verify_ssl` (how are these things different?) to `true` in `config.yml` and the warnings went away.

Do you have any idea what might have set these flags to false (my only hypothesis is Anaconda Navigator?) as I'm pretty sure I've never manually edited this file before...

**Comment by AlbertDeFusco** [comment]
Something may have changed somewhere recently with anaconda-client. Are you able to test that on a completely fresh Anaconorda/Miniconda install without any of the standard config dirs?

**Comment by jlstevens** [comment]
> Are you able to test that on a completely fresh Anaconorda/Miniconda install without any of the standard config dirs?

I guess I could create a new user on my laptop then install miniconda to see if this reappears...

**Comment by AlbertDeFusco** [comment]
I'll try to test that as well. For now I'm going to let those two failed test combinations slide

**Pull request merged**
