### PR TITLE
Empty environment on init

### PR DESCRIPTION
**Pull request by AlbertDeFusco**
With this PR `anaconda-project init` will write an empty `packages:` key to the anaconda-project.yml file.

Since Conda version 4.6 empty environments have been supported.

```
>anaconda-project init
Project configuration is in /Users/adefusco/Development/AnacondaPlatform/anaconda-project/examples/init-me/anaconda-project.yml
>anaconda-project list-packages
Conda packages for environment 'default':



>anaconda-project prepare
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/adefusco/Development/AnacondaPlatform/anaconda-project/examples/init-me/envs/default



Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
#
# To activate this environment, use
#
#     $ conda activate /Users/adefusco/Development/AnacondaPlatform/anaconda-project/examples/init-me/envs/default
#
# To deactivate an active environment, use
#
#     $ conda deactivate

The project is ready to run commands.
Use `anaconda-project list-commands` to see what's available.

>anaconda-project add-packages python=3.8 flask
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/adefusco/Development/AnacondaPlatform/anaconda-project/examples/init-me/envs/default

  added / updated specs:
    - flask
    - python=3.8

...

Executing transaction: ...working... done
Using Conda environment /Users/adefusco/Development/AnacondaPlatform/anaconda-project/examples/init-me/envs/default.
Added packages to project file: python=3.8, flask.
```

### CODE REVIEW

**Review by jbednar — APPROVED** [review]
Looks good! I couldn't quite follow the implementation of `--empty-environment`; is it implemented in a backwards-compatible way? I see that it's deprecated, but is it respected?

Otherwise seems like a much better default.

**Comment by AlbertDeFusco** [comment]
`--empty-environment` is allowed but completely ignored since it is already the default behavior. I left it in for backwards compatibility of the command line.

**Comment by jbednar** [comment]
In that case should the docs mention how people would replicate the behavior from previous releases where `--empty-environment` was False by default?

**Comment by AlbertDeFusco** [comment]
Will do. I'm making a changelog and maintenance PR to close out the release

**Pull request merged**
